// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_imageSizeChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_imageSizeChange));
        
        string IMigrationMetadata.Id
        {
            get { return "202105231144384_mig_imageSizeChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
